### ISSUE TITLE
Send unicode file name turns into 'ATT001'

### ISSUE THREAD

**Issue by adiaviv05** [lavr/python-emails#12]
Hi,

is it possible to send a unicode file name?
Let say my file name is "שלום.docx" after sending it will be translated to "ATT00001.docx".

Please let me know if this possible at all.

**Comment by lavr** [comment]
Hi!
There is a bug in python-email, sorry.
I've fixed it in 7e6c4ebb2823b5abf77998cc34e3fc3592597aa4 
Version v0.1.13 already on pypi.
