### ISSUE TITLE
Sending the same mail twice

### ISSUE THREAD

**Issue by koraxis** [lavr/python-emails#121]
Hi,

I am trying to send a mail with a zip file attached. When it is a PDF or Text file everything is working as expected, but when i send a zip file it sends the same mail twice. This is how i send a mail with a zip file attached:

`message = emails.html(html="<p>Hi<br>Attached is the Monthly Availability and Latency report.",
                       subject="Test Subject2018",
                       mail_from=('Sender','sender@sender.com'))`

`message.attach(content_disposition="inline",data=open('E:\Availability\Test.zip', 'rb'), filename='Test.zip')`

`r = message.send(to='test@test.com', smtp={'host': 'mail.mnet-online.de', 'timeout': 5})`

**Comment by melvinev** [comment]
Having the same issue! Did you ever resolve?

**Comment by lavr** [comment]
Sorry for late answer.

I'm quite sure this is not a bug in `emails`.

My points:
- there is unittests sending email via real smtp servers
- I use this library in production for years, with all type of files including zip

If you really sure there is a bug, please, give more descriptive steps to reproduce or debug logs or mail server logs and reopen this issue
