### ISSUE TITLE
mail_from didn't fit office365

### ISSUE THREAD

**Issue by Rand01ph** [lavr/python-emails#123]
From office365

This article describes improvements that are being made to the SMTP Authenticated Submission client protocol that will be rolled out beginning September 1, 2018.

submission behavior could change if the Reply or Mail From address isn't surrounded by angle brackets ("<" and ">") or if the sender display name contains an invalid character, such as the at sign (@), that isn't surrounded by quotation marks. Printers or devices that don’t fully adhere to the RFC standard can generate sending errors.

This can often be fixed by updating the settings on the device or printer by adding angle brackets ("<" and ">") around the Reply or Mail From address.

**Comment by Rand01ph** [comment]
@lavr  yes, i have build message like this:

`    m = emails.Message(html=mail_content, subject=mail_subject, mail_from=(mail_sender_name, 'test@outlook.com'), cc=cc_list,
                       bcc=bcc_list)
`

after office365 change the rule, i must change code to:
`
 m = emails.Message(html=mail_content, subject=mail_subject, mail_from=(mail_sender_name, '<test@outlook.com>'), cc=cc_list,
                       bcc=bcc_list)
`

**Comment by lavr** [comment]
I guess it is old and not actual anymore.

But I've read article https://docs.microsoft.com/en-us/exchange/troubleshoot/send-emails/smtp-submission-improvements 
I don't know what is "SMTP Authenticated Submission client protocol" - is it about smtp or not.
`emails.Message` generates valid address headers - it quotes display name and adds brackets by default, so you should have not add brackets to email yourself:
```
>>> emails.Message(html='x', subject='y', mail_from=('z@z.z', 'test@outlook.com')).as_bytes()
...
From: "z@z.z" <test@outlook.com>
...
```
