### ISSUE TITLE
Plain text and HTML alternative

### ISSUE THREAD

**Issue by aanriot** [lavr/python-emails#125]
Hello,

Regarding https://gist.github.com/lavr/fc1972c125ccaf4d4b91, I have the feeling that the library allows to embed a plain text version of the message, as well as a HTML alternative.

Though, it currently only renders base64-encoded parts on my side, without plain text.

Could you tell me if I missed something?

Thanks.

**Comment by lavr** [comment]
Hi!

`Message` class renders content of `text` attribute as `text/plain` part of message, example:

    >>> import emails; print(emails.html(html="<p>html part", text="text part", subject="subject", mail_from='a@b.c').build_message())
    From nobody Tue Feb 12 23:45:55 2019
    Content-Type: multipart/mixed; boundary="===============6725541663181665273=="
    MIME-Version: 1.0
    Date: Tue, 12 Feb 2019 23:45:55 +0300
    Subject: subject
    From: a@b.c

    This is a multi-part message in MIME format.

    --===============6725541663181665273==
    Content-Type: multipart/related;
     boundary="===============6549323180237045820=="
    MIME-Version: 1.0

    --===============6549323180237045820==
    Content-Type: multipart/alternative;
     boundary="===============0540981126387945411=="
    MIME-Version: 1.0

    --===============0540981126387945411==
    Content-Type: text/plain; charset="utf-8"
    MIME-Version: 1.0
    Content-Transfer-Encoding: base64

    dGV4dCBwYXJ0

    --===============0540981126387945411==
    Content-Type: text/html; charset="utf-8"
    MIME-Version: 1.0
    Content-Transfer-Encoding: base64

    PHA+aHRtbCBwYXJ0

    --===============0540981126387945411==--

    --===============6549323180237045820==--

    --===============6725541663181665273==--

If you have to use non-base64 encoding of `text/plain`, you should rewrite `Message._build_text_part`  in your successor class.

**Comment by aanriot** [comment]
Ok, thanks @lavr .
