### ISSUE TITLE
How can I test e-mail sending without actually sending the e-mails?

### ISSUE THREAD

**Issue by omrihar** [lavr/python-emails#135]
I would like to set up testing in my project so that I can see what e-mails are generated, and where they are sent, without actually sending out e-mails. 
Is there an easy way to set up some test fixtures for this? Is there a TestClient that I can use without having to bother the main application with distinguishing whether it's in a testing environment or production environment?

Thank you!
Omri

**Comment by lavr** [comment]
Hi! 
Here is test example: 
https://github.com/lavr/python-emails/blob/master/emails/testsuite/message/test_message.py#L207

**Comment by omrihar** [comment]
Thanks! We tried to implement this but we get an module import error:
`E   ModuleNotFoundError: No module named 'emails.backend.inmemory'`.
It would seem that the version released on pypi is `0.5.15`, whereas the version on github is `0.6`. Was this added to `0.6`?

**Comment by lavr** [comment]
Actually this module wasn't listed in setup.py, so it is wasn't packaged in any pypi release %(

**Comment by lavr** [comment]
I suggest you can just create your own backend class based on this code: https://github.com/lavr/python-emails/blob/master/emails/backend/inmemory/__init__.py

**Comment by omrihar** [comment]
Thank you! we'll do that...
