### ISSUE TITLE
Unable to inject variables into html template

### ISSUE THREAD

**Issue by manobeeslaar** [lavr/python-emails#137]
Hi There, 

I have search the internet for a solution, but unable to use a template and inject variables into it from python to the HTML template:
Example:
In the HTML template:
<h1>Hi {name}</h1>

Unable to add the name = name from python code.

Thank you and a great piece of software app.

Regards,

**Comment by lavr** [comment]
Hi! 
Can you show a piece of code?

**Comment by manobeeslaar** [comment]
Thank you!
PYTHON section:
```
store = 'ALL'
name = 'Mano'

message = emails.html(html=open('email_template.html'),
                     subject='SOH AGING - '+store,
                     mail_from=('URB SOH Management', 'mano@urb.co.za'))


message.attach(data=open('SOHAgingPerStore.xlsx', 'rb'), filename='SOHAgingPerStore.xlsx')
message.attach(data=open('logo.png', 'rb'), filename='logo.png')
message.attachments['logo.png'].is_inline = True
message.transformer.synchronize_inline_images()
message.transformer.save()
```
HTML:
`<div class = container>
      <p>Y'ello {name},</p>
    </br>
      <p>Attached you will find the store's stock aging:</p>
    </br>
      <p>Please take note of the below colors:</p>
    </br>
    <ul>
      <li>0 - 14 days WHITE</li>
      <li style="color: #C4D79B">15 - 27 days GREEEN</li>
      <li style="color: #DA9694">28 - 44 days LIGHT RED</li>
      <li style="color: #C00000">45+ days</li>
    </ul>
  </br>`

Hope this gives more insight!  Thank you,

**Comment by lavr** [comment]
You should use template object and pass variables to `render` method as shown in section "Use templates" in [docs](https://python-emails.readthedocs.io):
![image](https://user-images.githubusercontent.com/129239/63778971-7a3b7780-c8ee-11e9-9a29-a59f5aa02586.png)

**Comment by manobeeslaar** [comment]
Understood, but how do you render the template from a file as per code:
`message = emails.html(html=open('email_template.html'),`

I have tried to replace the open with the T -> `html=T('email_template.html')`, but this does not work.
Apologies for the questions, but I am trying to wrap my head around this.
Thank you!

**Comment by lavr** [comment]
T(open('email_template.html').read())

**Comment by manobeeslaar** [comment]
Thank you, closing ticket!
