### ISSUE TITLE
Library does not support RFC 6532 (non ascii characters in local part of the email address)

### ISSUE THREAD

**Issue by HHK1** [lavr/python-emails#138]
The `sanitize_address` function in the utils file imports and makes use of the `formataddr` function from the stdlib.

According to [this thread ](https://bugs.python.org/issue25955), the `formataddr` should no longer be used:

> formataddr is part of the legacy interface and has no knowledge of the current policy.  So it doesn't support RFC 6532.  For that you need to use the new API: just assign your address to the appropriate field, or create a headerregistry.Address object.

Because of this, it is impossible to send emails to addresses such as **`anaïs@example.com`** with this package, although it should be possible to send an email to such an address using a smtp server supporting SMTPUTF8. (At least according to [RFC 6532](https://tools.ietf.org/html/rfc6532))

**Comment by Ousret** [comment]
PR #142 might be related. This package need to encode decoded string in Message object.
ping @lavr could you review my proposal ?
