### ISSUE TITLE
Push v0.6 to PyPI

### ISSUE THREAD

**Issue by fdemello** [lavr/python-emails#139]

**Comment by sochi** [comment]
Hello @lavr, do you think you could possibly push the v0.6 version to PyPI?

(If you would need any assistance with that I could give you a hand I guess, though not a PyPI expert myself.)

**Comment by melvinev** [comment]
This would be great, any progress here?

**Comment by Ousret** [comment]
Would be great.

**Comment by mck9** [comment]
@lavr isn't active anymore?

**Comment by tingkai-zhang** [comment]
I wish @lavr all well.
It seems that he has not been active for a while. 
I was wondering if the community wants to create a fork of this project and continue on with it.

**Comment by lavr** [comment]
Not much activity here, this is true.
But pypi is not so important nowadays, I think.
For me personally `git+https://github.com/<repo>` in requirements works fine for production projects.

**Comment by lavr** [comment]
0.6 pushed to repo
