### ISSUE TITLE
Save sent message as HTML

### ISSUE THREAD

**Issue by andyfaizan** [lavr/python-emails#141]
Hi! I am currently using Jinja templates to generate the HTML for the mails and attach images using `message.attach`. I want to save the resultant `message` as HTML (which I would then convert to PDF). Is there a way to do this? I tried using [Weasyprint](https://weasyprint.readthedocs.io/en/stable/index.html) but its giving me a hard time with getting all pages and styling.

**Comment by lavr** [comment]
Hi! 
I guess this question is out of python-emails scope. 
My opinion: you probably should use same Jinja template directly to generate html, without generating email message.
But if you definitly need to convert email message to html, then you can write convertor tool yourself.

**Comment by andyfaizan** [comment]
Hi!
Alright. Thanks for the quick response!
