### ISSUE TITLE
Clarify license of this project

### ISSUE THREAD

**Issue by ambroisie** [lavr/python-emails#165]
Hello, it seems like the [LICENSE](https://github.com/lavr/python-emails/blob/1c202b738dc9221d3ad6962b27965914a46c6395/LICENSE) file is for Apache 2.0, but [setup.py:137](https://github.com/lavr/python-emails/blob/1c202b738dc9221d3ad6962b27965914a46c6395/setup.py#L137) says it should be BSD.

Which one is it? Is it both?

**Comment by lavr** [comment]
Hello!
It is Apache 2.0
