### ISSUE TITLE
Using this library with SMTP servers that require authentication

### ISSUE THREAD

**Issue by DeepSpace2** [lavr/python-emails#37]
Hi, is this possible to use this library with SMTP servers that require authentication? 
I've tried passing "username" and "password" keys to the smtp dictionary but I get an "unexpected keyword argument" exception.

I've looked into it and it looks like SMTPClientWithResponse.__init__() should also wrap smtplib's login() method somehow.

Thanks :)

```python
m = emails.Message(text="text",  subject="subject",  mail_from=("CI", "ci@mycompany.com"))
response = m.send(to='aa@gmail.com',
                               smtp={"host":"smtp.gmail.com", "port": 465, "ssl": True, "username": "user",  
                               "password": "pass"})

**Comment by DeepSpace2** [comment]
My bad, the correct key is "user" and not "username", then it works perfect :).

**Comment by lavr** [comment]
You're welcome ;)
