### ISSUE TITLE
DKIM issues

### ISSUE THREAD

**Issue by Garito** [lavr/python-emails#44]
Hi, I'm trying to sign my emails with DKIM but some issues or misunderstandings prevent me to do so
This lines are in my flask config file:

DKIM_KEY = open('/dkim/timefounder.com.pem')
DKIM_DOMAIN = 'timefounder.com'
DKIM_SELECTOR = 'mail'

Then I try to use it like:
```python
if current_app.config.get('DKIM_KEY', False):
		msg.dkim(key=current_app.config['DKIM_KEY'], 
				domain=current_app.config['DKIM_DOMAIN'], 
				selector=current_app.config['DKIM_SELECTOR'])
```
But this error is raised:
Exception on /users/send_invitation [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_principal.py", line 199, in _decorated
    rv = f(*args, **kw)
  File "/app/Users/__init__.py", line 166, in send_invitation
    send_mail(title, data, recipients)
  File "/app/TimeFounder/utils.py", line 17, in send_mail
    selector=current_app.config['DKIM_SELECTOR'])
  File "/usr/local/lib/python2.7/dist-packages/emails/message.py", line 391, in dkim
    self._dkim_signer = self.dkim_cls(**kwargs)
TypeError: __init__() takes at least 4 arguments (3 given)

Giving the fact that I used this from the examples:
message.dkim(key=open('my.key'), domain='mycompany.com', selector='newsletter')

Could someone point me where the error is?

Thanks a lot!

**Comment by lavr** [comment]
Try `privkey` parameter instead of `key`:

    msg.dkim(privkey=current_app.config['DKIM_KEY'], ...

**Comment by Garito** [comment]
Yeah that solves the problem

Need to point out, thought, that the privkey=open stuff is a problem: if you put the open there and send more than one messages it fails (the first works but the next will not if you dont seek(0) the dkim file first)

Hope you could understand this and change the examples

BTW thanks a lot again I'm super glad to have changed to your library

**Comment by lavr** [comment]
> if you put the open there and send more than one messages it fails (the first works but the next will not if you dont seek(0) the dkim file first)

I'll check if.

**Comment by lavr** [comment]
I guess you pass the same open file to different Message objects.
In this scenario you should do seek(0) yourself.

But notice you can pass string as a priv_key, so you can read file once, i.e.:

     key = open(current_app.config['DKIM_KEY_FILE'], 'rb').read()
     ...
     msg.dkim(priv_key=key, ...)

**Comment by Garito** [comment]
Yeah, that was the point
You only need to update the docs...

**Comment by lavr** [comment]
Garito, thank you for your bugreports.

BTW, you can always give a star to this repository :)

**Comment by Garito** [comment]
Done!!!
