### ISSUE TITLE
How authenticate SMTP server ?

### ISSUE THREAD

**Issue by ebin123456** [lavr/python-emails#53]
How can i send email from gmail using this module ?

**Comment by lavr** [comment]
Hi! 
Here is example settings to send email via Google Apps smtp from plain python program:

    message = emails.Message(...)
    r = message.send(to=('John Brown', 'jbrown@gmail.com'),
                     smtp={'host':'smtp.gmail.com', 'port': 465, 'ssl': True, 'user': '<gmail-login>', 'password': '<gmail-password>'})
