### ISSUE TITLE
Multiple recipients on 'to='

### ISSUE THREAD

**Issue by switchuserdo** [lavr/python-emails#54]
Hello Mr. Lavrinenko, 

I recently found your code on GitHub and am really enjoying the work you have done on creating the python library for emails!

But I was wondering how to add multiple recipients on the 

to=

line.

Thank You for all your hard work!

**Comment by switchuserdo** [comment]
Thank You!

Also, is adding 

Cc
Bcc

to the message possible?

**Comment by lavr** [comment]
Version with multiple recipients is on pypi.

**Comment by switchuserdo** [comment]
for me the below code will not work...



import emails



message = emails.html(html=open('Newsletter.html'),

                      subject='Newsletter',

                      mail_from=('ME', 'me@1.com'))



m = Message(mail_to=['someemail1.com', 'someemail2@.com'],



# Send and get response from smtp server:



r = message.send(to=('myaddress.com'),

                 render={'name': 'Elise'},

                 smtp={'host':'smtp.somecompany.com', 'port': 25, 'tls':
True})

assert r.status_code == 250

**Comment by lavr** [comment]
Sorry, your code formatting is missing.

This should work as you expected with emails v0.5.4:

    import emails
    m = emails.Message(mail_from='a@company.com', subject='...', html='...')
    r = m.send(mail_to=['b@gmail.com', c@gmail.com'], ...)

**Comment by switchuserdo** [comment]
Do you by chance have any more examples? 
this isn't working either:

import emails

with open('Newsletter.html') as file:
    data = file.read()

m = emails.Message(mail_from='me@1.com',
                   mail_to=[("Johnny", "johnny@2.com"),("me", "me@1.com")],
                   subject='Newsletter',html=data)
m.send()

**Comment by lavr** [comment]
Can you explain what exactly does not work in your example?
Is there error with traceback?
Or invalid headers in result message?
