### ISSUE TITLE
Import jinja template from external file

### ISSUE THREAD

**Issue by dalepotter** [lavr/python-emails#74]
Hi, nice library!

Is it possible to import a template from an external file (for example `template.html`)?  I've adapted the example code in the docs, but am getting a `TypeError` - see below.

If this is possible, I'm happy to send a pull request to extend the docs examples.

**sendemail.py**

```
import emails
from emails.template import JinjaTemplate as T

message = emails.html(
     subject=T('Payment Receipt No.{{ billno }}'),
     html=T(open('template.html')),
     mail_from=('ABC', 'robot@mycompany.com')
     )

r = message.send(...)
```

This gives: 
```
$ python sendemail.py
Traceback (most recent call last):
... 
TypeError: Can't compile non template nodes
```

**Comment by lavr** [comment]
Hi!

JinjaTemplate constructor receives unicode string as first argument, so try ```T(open('template.html').read())``` 

For non-ascii content you should probably decode text to unicode: ```T(open('template.html').read().decode('latin-1'))```
