### ISSUE TITLE
Is Python 3.5 supported?

### ISSUE THREAD

**Issue by vfaronov** [lavr/python-emails#86]
I’d like to use Emails under Python 3.5, but I notice that, unlike 3.4 and 3.6, it’s missing from your [Tox config](https://github.com/lavr/python-emails/blob/d9c604d81eb9f13c3483999ba26df655d53590ba/tox.ini), which explicitly says “all supported python versions”, as well as from [Travis config](https://github.com/lavr/python-emails/blob/d9c604d81eb9f13c3483999ba26df655d53590ba/.travis.yml) and [trove classifiers](https://github.com/lavr/python-emails/blob/d9c604d81eb9f13c3483999ba26df655d53590ba/setup.py#L142-L144) (though 3.6 is missing from the latter, too).

Are there any known problems with using Emails under Python 3.5?

**Comment by shireen91** [comment]
is python 3.6 supported?

**Comment by lavr** [comment]
Yes
